# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/conanpro',
                'doc_host': 'https://fenke.github.io',
                'git_url': 'https://github.com/fenke/conanpro',
                'lib_path': 'conanpro'},
  'syms': {'conanpro.core': {'conanpro.core.foo': ('core.html#foo', 'conanpro/core.py')}}}
